#!/usr/bin/env bash
#
# Execute Flow using Twilio Studio API
#
# Use curl and bash so we don't have to install any extra
# python libraries into our Home Assistant server.

# First, load our Twilio credentials. Change /config to
# the path to your installation's configuration directory.
conf_d=${conf_d:-/config}

credentials_file=${secrets_f:-$conf_d/twilio-credentials.sh}
time=`date '+%Y_%m_%d__%H_%M'`;
# Now we load TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN and TWILIO_FLOW from $credentials_file
source "$credentials_file"

recipient_number=$1
twilio_flow=$2

exec curl -X POST https://studio.twilio.com/v1/Flows/${twilio_flow}/Executions \
    --data-urlencode "To=${recipient_number}" \
    --data-urlencode "From=${TWILIO_NUMBER}" \
    --data-urlencode "Parameters={\"audio\":\"http://192.168.1.250:8123/local/audio/$time.mp3\"}" \
    -u "${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}"