# lovelace_gen

#==========================================
#=== SETTINGS WARNING
#===
#=== entity: Boolean to warn about
#=== name:   The text of the warning message
#==========================================
type: custom:button-card
entity: input_boolean.irrigation_testing_mode
name: >
  [[[
    if (states['{{ entity }}'].state == 'on')
      return '{{ name }}';
  ]]]
styles:
  grid:
    - grid-template-areas: '"n"'
    - grid-template-columns: 1fr
    - grid-template-rows: min-content
  card:
    - display: >
        [[[
          if (states['{{ entity }}'].state != 'on')
            return 'none';
          else return null;
        ]]]
    - height: 2.5em
    - font-family: >
        [[[
          return states['input_text.irrigation_ui_font_family'].state
        ]]]
    - font-size: 12px
    - box-shadow: none
    - background-color: transparent
    - padding-top: 0em 
    - margin-top: 0em
    - margin-bottom: 0em
  name:
    - color: var(--accent-color)
    - justify-self: right
    - padding-right: 0.75em
tap_action:
  action: none
state:
  - value: 'on'
    styles:
      card:
        - animation: blink 2s ease 1s 3
