binary_sensor:
  - platform: gpio
    id: pavlina_email
    name: Pavlina Email Scan
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - homeassistant.service:
            service: switch.turn_on
            data:
              entity_id: switch.pdf2mail_pavlina
        - delay: 1s
        - homeassistant.service:
            service: switch.turn_off
            data:
              entity_id: switch.pdf2mail_pavlina
  - platform: gpio
    id: makis_email
    name: Makis Email Scan
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - homeassistant.service:
            service: switch.turn_on
            data:
              entity_id: switch.pdf2mail_makis
        - delay: 1s
        - homeassistant.service:
            service: switch.turn_off
            data:
              entity_id: switch.pdf2mail_makis
  - platform: gpio
    id: thanasis_email
    name: Thanasis Email Scan
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - homeassistant.service:
            service: switch.turn_on
            data:
              entity_id: switch.pdf2mail_thanasis
        - delay: 1s
        - homeassistant.service:
            service: switch.turn_off
            data:
              entity_id: switch.pdf2mail_thanasis
  - platform: gpio
    id: print
    name: Print
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - homeassistant.service:
            service: switch.turn_on
            data:
              entity_id: switch.pdf2print_makis
        - delay: 1s
        - homeassistant.service:
            service: switch.turn_off
            data:
              entity_id: switch.pdf2print_makis
        # - homeassistant.service:
        #     service: switch.turn_on
        #     data:
        #       entity_id: switch.switchbot
        # - delay: 1s
        # - homeassistant.service:
        #     service: switch.turn_off
        #     data:
        #       entity_id: switch.switchbot