wifi:
  networks:
  - ssid: "Tardis"
    password: !secret wifi_password
  - ssid: "HOME"
    password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${upper_devicename} Hotspot
    password: !secret wifi_password