- platform: manual
  name: Home Alarm
  code: !secret alarm_code
  code_arm_required: false
  arming_time: 30
  delay_time: 10
  trigger_time: 300
  disarmed:
    trigger_time: 0
  armed_home:
    arming_time: 0
    delay_time: 0