- platform: template
  sensors:
    humidifier_state:
      friendly_name: "Humidifier State"
      value_template: >-
        {{states('humidifier.eva_ii')}}

- platform: ping
  host: !secret health_check_io
  name: "HA Online"
  count: 5
  scan_interval: 300

# - platform: sun2
#   monitored_conditions:
#     - elevation

# - platform: template
#   sensors:
#     rfid_doorstatus_inverted:
#       value_template: >-
#         {{ is_state('binary_sensor.doorstatus', 'off') }}
#       friendly_name: Κατάσταση
#       device_class: door
