- platform: snmp
  name: Temperature Thanasis Camera
  host: 192.168.1.107
  baseoid: iso.3.6.1.4.1.8072.1.3.2.4.1.2.9.71.86.45.66.88.50.55.48.48.5
  username: geovision2020
  auth_key: H%bASm%e#fC4+QP
  auth_protocol: hmac-md5
  version: '3'
  value_template: '{{ value | regex_findall_index("(\d+.\d+)")}}'
  unit_of_measurement: '°C'
  accept_errors: true

# - platform: snmp
#   name: Temperature Veranda Camera
#   host: 192.168.1.106
#   baseoid: iso.3.6.1.4.1.8072.1.3.2.4.1.2.7.86.101.114.97.110.100.97.5
          
#   username: geovision2020
#   auth_key: 9wUe!u365ACVAG^$
#   auth_protocol: hmac-md5
#   version: '3'
#   value_template: '{{ value | regex_findall_index("(\d+.\d+)")}}'
#   unit_of_measurement: '°C'
#   accept_errors: true

# - platform: snmp
#   name: Temperature Veranda Camera Raw
#   host: 192.168.1.106
#   baseoid: 3.6.1.4.1.8072.1.3.2.4.1.2
#   username: geovision2020
#   auth_key: 9wUe!u365ACVAG^$
#   auth_protocol: hmac-md5
#   version: '3'
  # accept_errors: true
# - platform: snmp
#   name: Test
#   host: 192.168.1.103
#   baseoid: 
#   username: geovision2020
#   auth_key: P7Cwt9u!^T2wvyt!
#   auth_protocol: hmac-md5
#   version: '3'
#   value_template: '{{ value | regex_findall_index("(\d+.\d+)")}}'

# - platform: snmp
#   name: Test
#   host: 192.168.1.102
#   baseoid: 
#   username: geovision2020
#   auth_key: 5_rJTS=hAPuQDmYU
#   auth_protocol: hmac-md5
#   version: '3'
#   value_template: '{{ value | regex_findall_index("(\d+.\d+)")}}'

# - platform: snmp
#   name: Test
#   host: 192.168.1.101
#   baseoid: 
#   username: geovision2020
#   auth_key: W5V_fzHjm=KQ9=?X
#   auth_protocol: hmac-md5
#   version: '3'
#   value_template: '{{ value | regex_findall_index("(\d+.\d+)")}}'

# iso.org.dod.internet.snmpV2.snmpModules.10.1.2.2

# .iso.org.dod.internet.mgmt.mib-2.25.3.9.
# .iso.org.dod.internet.snmpV2.snmpModules.snmpMIB
# - platform: mqtt
#   name: "Kerbeors Video Path"
#   state_topic: "kios/mqtt"
#   value_template: "{{ value_json.pathToVideo }}"
#   expire_after: 3600