# lovelace_gen

#===================================
#=== SMARTWEATHER STATION CHECK BOX
#===================================
type: custom:button-card
entity: {{ entity }}
name: >
  [[[
    var entity = '{{ entity }}';
    var code = entity.slice(-1);
    return states['input_text.smartweather_location_code' + code].state;
  ]]]
show_label: true
label: >
  [[[
    var entity = '{{ entity }}';
    var code = entity.slice(-1);
    var stn_name = states['sensor.smartweather_' + code].attributes.station_name;
    return stn_name != null ? stn_name : 'UNAVAILABLE';
  ]]]
icon: mdi:check-box-outline
size: 50%
styles:
  grid:
    - grid-template-areas: '"n i" "l l"'
    - grid-template-columns: 'min-content 45%'
  img_cell:
    - justify-content: start
  card:
    - height: 3.5em
    - margin-top: -0.5em
    - font-size: 14px
    - box-shadow: none
    - background: none
    - font-family: >
        [[[
          return states['input_text.irrigation_ui_font_family'].state
        ]]]
  name:
    - height: 1em
    - justify-self: left
    - padding: 0em 0.5em 0em 0em
  label:
    - justify-self: left
    - font-size: 10px
    - padding: 0em 0em 0em 0em
state:
  - value: 'off'
    icon: mdi:checkbox-blank-outline
    styles:
      card:
        - color: var(--secondary-text-color)
        - opacity: 50%
      icon:
        - color: var(--secondary-text-color)
