
#===============================================
#=== FORECAST HIGH VS. ACTUAL TEMPERATURE GRAPH
#===============================================
type: custom:mini-graph-card
entities:
  #=== FORECAST
  - entity: sensor.irrigation_sensor_forecast_rain
    color: IndianRed
    show_legend: false
  #=== ACTUAL
  - entity: sensor.irrigation_sensor_rainfall_today
    color: SteelBlue
    show_legend: false
  #=== DAY/NIGHT
  - entity: binary_sensor.above_horizon
    name: Night
    y_axis: secondary
    color: black
    show_line: false
    show_points: true
    show_legend: false
lower_bound: 0
line_width: 2
hours_to_show: 48
points_per_hour: 4
aggregate_func: min
show:
  fill: fade
  name: false
  state: false
  labels: false
  points: false
  labels_secondary: false
  icon: false
state_map:
  - value: 'on'
    label: 'Day'
  - value: 'off'
    label: 'Night'
tap_action:
  action: none
card_mod:
  style: >
    ha-card {
      box-shadow: none;
      background: none;
      border-radius: 0px;
    }
    .flex {
      padding: 0em
    }

