
#=========================
#=== TEMPERATURE SETTINGS
#=========================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== TEMPERATURE SETTINGS
      - type: custom:button-card  
        show_icon: false
        name: TEMPERATURE SETTINGS
        tap_action:
          action: none

        #=== ANCHOR STYLES FOR ALL HEADINGS ON THE PAGE
        styles: &title_style
          card:
            - color: var(--secondary-text-color)
            - box-shadow: none
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 18px
          name:
            - justify-self: start
            - border-left: 3px solid var(--accent-color)
            - padding-left: 0.5em

      #=== NUMBER OF DAYS TO USE
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_temp_history_used
            name: Number of days history to use
            label: (0 to 4) If zero only the temperature today is used

      #=== TEMPERATURE BASELINE
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_baseline
            name: Baseline temperature
            label: Exceeding this temperature increases the watering time
            padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== TEMPERATURE DATA
      - type: custom:button-card  
        show_icon: false
        name: TEMPERATURE DATA
        tap_action:
          action: none
        styles: *title_style

      #=== TEMPERATURE MULTIPLIER
      - !include
          - ../item_settings_multiplier_line.yaml
          - entity: input_number.irrigation_temp_multiplier
            name: "Current Multiplier ( ℹ️ )"
            label: Calculated based on temperature and baseline

      #=== HIGHEST FORECAST HIGH TEMPERATURE TODAY
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_highest_forecast_high_temp_today
            name: Highest forecasted temperature today
            round: 1
            tap_action: none

      #=== HIGHEST ACTUAL TEMPERATURE TODAY
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_highest_actual_temp_today
            name: Highest actual temperature recorded today
            round: 1
            tap_action: none
            padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== FORECAST HIGH VS. ACTUAL TEMPERATURE
      - type: custom:button-card  
        show_icon: false
        name:  HIGH TEMPERATURE - <font color=IndianRed>Forecast</font> vs. <font color=SteelBlue>Actual</font>
        tap_action:
          action: none
        styles: *title_style

      #=== FORECAST VS. ACTUAL HIGH TEMPERATURE GRAPH
      - !include item_settings_temperature_graph.yaml

      #=== USE FORECAST HIGH TEMPERATURE
      - !include item_settings_use_forecast_high_temp.yaml

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== TEMPERATURE HISTORY
      - type: custom:button-card  
        show_icon: false
        name: HIGH TEMPERATURE HISTORY
        tap_action:
          action: none
        styles: *title_style

      #=== HIGH TEMPERATURE YESTERDAY
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_1
            name: Yesterday
            round: 1
            tap_action: none

      #=== HIGH TEMPERATURE 2 DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_2
            name: Two days ago
            round: 1
            tap_action: none

      #=== HIGH TEMPERATURE 3 DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_3
            name: Three days ago
            round: 1
            tap_action: none

      #=== HIGH TEMPERATURE 4 DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_4
            name: Four days ago
            round: 1
            tap_action: none

card_mod:
  style: >
    ha-card {
      box-shadow: none;
    }
