substitutions:
  devicename: dwmatio_thanasis
  upper_devicename: Dwmatio Thanasis

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
  comment: "Motion sensor & scanner/printer buttons"

esp32_ble_tracker:

packages:
  wifi: !include common_substitutions/wifi.yaml
  device_base: !include common_substitutions/device_base.yaml
  buttons: !include common_substitutions/printer_scanner_buttons.yaml

status_led:
    pin: 16

binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "$upper_devicename PIR"
    device_class: motion