substitutions:
  devicename: garage_door
  upper_devicename: Garage Door

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit

packages:
  wifi: !include common_substitutions/wifi.yaml
  device_base: !include common_substitutions/device_base.yaml

status_led:
    pin: 16
    
logger:
  level: DEBUG
  logs:
    text_sensor: NONE
    sensor: NONE

# sensor:    
#   - platform: adc
#     pin: A0
#     name: "TEMT6000 Illuminance"
#     unit_of_measurement: lx
#     filters:
#       - lambda: |-
#           return (x / 10000.0) * 2000000.0;

#       - lambda: |-
#           return (( 0.25-( 0.000244140625 * x ))/(0.0048828125-x));


binary_sensor:
  - platform: gpio
    pin: GPIO04
    name: "PIR Sensor"
    device_class: motion
    
# sensor:
#   - platform: adc
#     pin: GPIO32
#     name: "Makis Petrelaio"
#     update_interval: 30s
#   - platform: adc
#     pin: GPIO33 
#     name: "Makis Petrelaio"
#     update_interval: 30s
#   - platform: adc
#     pin: GPIO35
#     name: "Makis Petrelaio"
#     update_interval: 30s
#     attenuation: 11db
    # filters:
    #   - lambda: |-
    #       return (( 0.25-( 0.000244140625 * x ))/(0.0048828125-x));