substitutions:
  devicename: kouzina_sensor
  upper_devicename: Kouzina

esphome:
  name: $devicename

  # on_loop:
  #   then:
  #     - lambda: delay(5);

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

packages:
  wifi: !include common_substitutions/wifi.yaml
  device_base: !include common_substitutions/device_base.yaml

esp32_ble_tracker:

sensor:
  # - platform: adc
  #   pin: GPIO32
  #   name: "$devicename Illuminance"
  #   unit_of_measurement: lx
  #   attenuation: 11db
  #   filters:
  #     - lambda: |-
  #         return (x / 10000.0) * 2000000.0;
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:C1:37:3C"
    bindkey: "2095c002889cf242a11625f856cbe59d"
    temperature:
      name: "Kouzina Temperature"
    humidity:
      name: "Kouzina Î—umidity"
    battery_level:
      name: "Kouzina Battery Level"

status_led:
  pin: GPIO2

binary_sensor:
  - platform: gpio
    pin: 13
    name: "$upper_devicename PIR"
    device_class: motion

output:
  - platform: ledc
    pin: GPIO32
    id: rtttl_out
rtttl:
  output: rtttl_out

api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
# sensor:
#  - platform: bme280
#    temperature:
#      name: "BME280 Temperature"
#      oversampling: 16x
#    pressure:
#      name: "BME280 Pressure"
#    humidity:
#      name: "BME280 Humidity"
#    address: 0x76
#    update_interval: 60s