substitutions:
  devicename: levitostasio
  upper_devicename: Levitostasio

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  includes:
    - shift_register_switch.h
  libraries:
    - ShiftRegister74HC595@1.2

packages:
  wifi: !include common_substitutions/wifi.yaml
  device_base: !include common_substitutions/device_base.yaml

switch:
  - platform: custom
    lambda: |-
      std::vector<switch_::Switch *> switches;
      for(int i = 0; i < 8; i++) {
          auto zone_switch = new ShiftRegisterSwitch(i);
          App.register_component(zone_switch);
          switches.push_back(zone_switch);
      }
      return switches;
    switches:
      -  name: "Levitostasio Relay 1"
         inverted: yes
      -  name: "Levitostasio Relay 2"
         inverted: yes
      -  name: "Levitostasio Relay 3"
         inverted: yes
      -  name: "Levitostasio Relay 4"
         inverted: yes
      -  name: "Levitostasio Relay 5"
         inverted: yes
      -  name: "Levitostasio Relay 6"
         inverted: yes
      -  name: "Levitostasio Relay 7"
         inverted: yes
      -  name: "Levitostasio Relay 8"
         inverted: yes

status_led:
    pin: 16

# binary_sensor:
#   - platform: gpio
#     pin: GPIO13
#     name: "PIR Sensor"
#     device_class: motion
#    on_press:
#      then:
#        - homeassistant.service:
#            service: light.turn_on
#            data:
#              entity_id: light.ypnodomatio
#        - delay: 10min
#        - homeassistant.service:
#            service: light.turn_off
#            data:
#              entity_id: light.ypnodomatio