substitutions:
  devicename: sprinkler-system
  upper_devicename: Sprinkler System

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
  
status_led:
  pin: GPIO2

packages:
  wifi: !include common_substitutions/wifi.yaml
  device_base: !include common_substitutions/device_base.yaml

esp32_ble_tracker:

logger:
  level: DEBUG
  logs:
    text_sensor: NONE
    sensor: NONE

sensor:
  - platform: dht
    pin: GPIO4
    model: DHT22
    temperature:
      name: "Garden Temperature"
    humidity:
      name: "Garden Humidity"
    update_interval: 30s
  - platform: dht
    pin: GPIO15
    model: DHT22
    temperature:
      name: "Sprinkler System Enclosure Temperature"
    humidity:
      name: "Sprinkler System Enclosure Humidity"
    update_interval: 30s
  - platform: adc
    pin: GPIO35
    id: moisture_sensor
    name: "Soil Moisture"
    unit_of_measurement: "%"
    update_interval: 10s
    attenuation: 11db
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          - 3.26 -> 0.0
          - 1.63 -> 100.0
      - lambda: |
          if (x < 0) return 0; 
          else if (x > 100) return 100;
          else return (x);

switch:
  - platform: gpio
    name: "$upper_devicename Relay 1"
    inverted: yes
    pin: GPIO23
  - platform: gpio
    name: "$upper_devicename Relay 2"
    pin: GPIO14
    inverted: yes
  - platform: gpio
    name: "$upper_devicename Relay 3"
    pin: GPIO27
    inverted: yes
  - platform: gpio
    name: "$upper_devicename Relay 4"
    pin: GPIO26
    inverted: yes
  - platform: gpio
    name: "$upper_devicename Relay 5"
    pin: GPIO25
    inverted: yes
  - platform: gpio
    name: "$upper_devicename Relay 6"
    pin: GPIO33
    inverted: yes
  - platform: gpio
    name: "$upper_devicename Relay 7"
    pin: GPIO32
    inverted: yes
  - platform: gpio
    name: "$upper_devicename Relay 8"
    pin: GPIO22
    inverted: yes